"""empty message

Revision ID: 091741c02168
Revises: 3bd66fcaf26f
Create Date: 2025-05-26 16:08:28.198223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091741c02168'
down_revision = '3bd66fcaf26f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokeballs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=100), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokeballs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
