"""empty message

Revision ID: 4459210c0c69
Revises: a5cffa318ac2
Create Date: 2025-05-14 12:43:39.848093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4459210c0c69'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon')
    # ### end Alembic commands ###
