"""empty message

Revision ID: ef67642a5219
Revises: 091741c02168
Create Date: 2025-05-27 10:09:20.677699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef67642a5219'
down_revision = '091741c02168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pokeballs_id', sa.Integer(), nullable=True))
        batch_op.alter_column('pokemon_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'pokeballs', ['pokeballs_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('pokemon_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('pokeballs_id')

    # ### end Alembic commands ###
